### ISSUE TITLE
Boolean for true/false values

### ISSUE THREAD

**Issue by GraysonBellamy** [ulfsri/pyAlicat#107]
## 🚀 Feature Request

For values that are true/false like if the device should save the setting on powerup, let's use a Boolean input so we don't have to parse a string and it's clearer to the user what should be given.

## 🔈 Motivation

Cleaner code and clarity in documentation

## 📎 Additional context

![image](https://github.com/ulfsri/pyAlicat/assets/51384453/5840f98e-92f8-4560-9a06-dbbe8f4e2bed)

**Comment by ULibrady** [comment]
Verified to be clear in all three device files
