### ISSUE TITLE
Firmware revisions functions

### ISSUE THREAD

**Issue by GraysonBellamy** [ulfsri/pyAlicat#95]
## 🚀 Feature Request

I remember in the manual the use of some functions depends on the firmware version of the device. Should we be checking for this to confirm the correct use. We have some older Alicats laying around so we want to be able to use them seamlessly.

## 🔈 Motivation

Compatibility with all devices.

**Comment by GraysonBellamy** [comment]
Some functions also seem to have a minimum version where they were introduced. This should be incorporated as well.

For instance, deadband_mode() can only be used on devices with firmware >=10.05:
![image](https://github.com/ulfsri/pyAlicat/assets/51384453/66e568b4-2c17-4fb0-a7bf-e92cc9f65ba8)

**Comment by ULibrady** [comment]
Each relevant function now verifies the version and will return if the device is too old.
