### ISSUE TITLE
Docstrings

### ISSUE THREAD

**Issue by GraysonBellamy** [ulfsri/pyAlicat#98]
## 🚀 Feature Request

Applies to all packages best let's standardize and generate consistent docstrings for all our code. I would recommend Google's python docstring style guide.
[https://google.github.io/styleguide/pyguide.html#s3.8.1-comments-in-doc-strings](https://google.github.io/styleguide/pyguide.html#s3.8.1-comments-in-doc-strings)

## 🔈 Motivation

Standardization of code and documentation to make everything understandable.

## 🛰 Alternatives

There's sphinx (reStructuredText) or numpy/scipy styles as well. I don't have a huge preference but let's just pick one.

**Comment by ULibrady** [comment]
Docstrings are all consistent
